name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-publish:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
            java-version: 11
            distribution: 'temurin'
            cache: 'maven'
        - run: mvn -B clean install --file pom.xml
        - run: mkdir staging && cp target/*.jar staging
        - uses: actions/upload-artifact@v3
          with:
            name: Package
            path: staging
